apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wmo2rcyso-dotnet-basic
  janus-idp.io/tekton: wmo2rcyso-dotnet-basic
  backstage.io/kubernetes-id: wmo2rcyso-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wmo2rcyso-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
